###show User data by project
#select project using params
GET http://localhost:3000/projects/seed/2.json


### List User commits on a project
GET http://localhost:3000/projects/user.json
Content-Type: application/json

{
"user_id": 1,
"project_id": 1
}

